[main]
name = "Universal Layout Standard Russian"
short_name = "ULSRU"

[msklc]
name = "ULSRU"
company = "braindefender"
copyright = "©2026 braindefender"
description = "Universal Layout Standard Russian"

[ligatures]
FatArr = "=>"
ThinArr = "->"

[layout]
base = '''
1        2        3        4        5        6        7        8        9        0
й        ц        у        к        е        н        г        ш        щ        з
ф        ы        в        а        п        р        о        л        д        ж
я        ч        с        м        и        т        ь        ,        .        ю
@Space   '        -        =        х        б        /        э        /        .
'''

base_shift = '''
!        @        #        $        %        ^        ?        *        (        )
Й        Ц        У        К        Е        Н        Г        Ш        Щ        З
Ф        Ы        В        А        П        Р        О        Л        Д        Ж
Я        Ч        С        М        И        Т        Ь        ;        :        Ю
@Space   "        _        +        Х        Б        |        Э        |        ,
'''

altgr = '''
¹        ²        ³        ⁴        ‰        ˆ        ¿        ∞        ‘        ’
ψ        ω        €        ®        ё        ¥        λ        @None    @None    π
α        §        °        £        γ        ₽        ø        @FatArr  «        »
μ        ×        ©        √        β        η        ъ        <        >        &
@Nbsp    `        –        ≠        [        ]        \        ~        \        .
'''

altgr_shift = '''
¡        ½        ⅓        ¼        @None    @None    ⁈        @None    “        ”
Ψ        Ω        €        ®        Ё        ¥        Λ        @None    @None    Π
Α        Σ        Δ        £        Γ        ₽        Ø        @ThinArr ←        →
Μ        @None    ¢        @None    Β        Η        Ъ        ≤        ≥        …
@Nbsp    •        —        ±        {        }        ¦        ≈        ¦        ,
'''

caps = '''
1        2        3        4        5        6        7        8        9        0
Й        Ц        У        К        Е        Н        Г        Ш        Щ        З
Ф        Ы        В        А        П        Р        О        Л        Д        Ж
Я        Ч        С        М        И        Т        Ь        ,        .        Ю
@Space   '        -        =        Х        Б        /        Э        /        .
'''

caps_shift = '''
!        @        #        $        %        ^        ?        *        (        )
й        ц        у        к        е        н        г        ш        щ        з
ф        ы        в        а        п        р        о        л        д        ж
я        ч        с        м        и        т        ь        ,        .        ю
@Space   "        _        +        х        б        |        э        |        ,
'''
