[main]
name = "English (US)"
short_name = "EN-US"
caps_is_shift = true

[msklc]
name = "EN-US"
company = "Unknown"
copyright = "©2026 Unknown"
description = "English (US)"
language_names = "English (United States)"

[layout]
base = '''
1        2        3        4        5        6        7        8        9        0
q        w        e        r        t        y        u        i        o        p
a        s        d        f        g        h        j        k        l        ;
z        x        c        v        b        n        m        ,        .        /
@Space   `        -        =        [        ]        \        '        \        .
'''

base_shift = '''
!        @        #        $        %        ^        &        *        (        )
Q        W        E        R        T        Y        U        I        O        P
A        S        D        F        G        H        J        K        L        :
Z        X        C        V        B        N        M        <        >        ?
@Space   ~        _        +        {        }        |        "        |        .
'''

caps = '''
@Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans
Q        W        E        R        T        Y        U        I        O        P
A        S        D        F        G        H        J        K        L        @Trans
Z        X        C        V        B        N        M        @Trans   @Trans   @Trans
@Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans
'''

caps_shift = '''
@Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans
q        w        e        r        t        y        u        i        o        p
a        s        d        f        g        h        j        k        l        @Trans
z        x        c        v        b        n        m        @Trans   @Trans   @Trans
@Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans
'''

altgr = '''
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
'''

altgr_shift = '''
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
'''
