[main]
name = "Russian (RU)"
short_name = "RU-RU"
caps_is_shift = true

[msklc]
name = "RU-RU"
description = "Russian (RU)"
copyright = "©2026 Unknown"
company = "Unknown"
locale_name = "ru-RU"
locale_id = "00000419"
language_names = "Russian (Russia)"

[macos]
bundle_id = "com.apple.keylayout"
bundle_name = "Russian (RU)"
bundle_version = "1.0"
keyboard_name = "RUKbName"
capslock_language_switch_capable = false
icon_is_template = false
input_source_id = "com.apple.keylayout.rukbname"
intended_language = "ru"
build_version = "1.0"
project_name = "Russian (RU)"
source_version = "1.0"

[layout]
base = '''
1        2        3        4        5        6        7        8        9        0
й        ц        у        к        е        н        г        ш        щ        з
ф        ы        в        а        п        р        о        л        д        ж
я        ч        с        м        и        т        ь        б        ю        .
@Space   ё        -        =        х        ъ        \        э        \        ,
'''

base_shift = '''
!        "        №        ;        %        :        ?        *        (        )
Й        Ц        У        К        Е        Н        Г        Ш        Щ        З
Ф        Ы        В        А        П        Р        О        Л        Д        Ж
Я        Ч        С        М        И        Т        Ь        Б        Ю        ,
@Space   Ё        _        +        Х        Ъ        /        Э        /        ,
'''

caps = '''
@Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans
Й        Ц        У        К        Е        Н        Г        Ш        Щ        З
Ф        Ы        В        А        П        Р        О        Л        Д        Ж
Я        Ч        С        М        И        Т        Ь        Б        Ю        @Trans
@Trans   Ё        @Trans   @Trans   Х        Ъ        @Trans   Э        @Trans   @Trans
'''

caps_shift = '''
@Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans   @Trans
й        ц        у        к        е        н        г        ш        щ        з
ф        ы        в        а        п        р        о        л        д        ж
я        ч        с        м        и        т        ь        б        ю        @Trans
@Trans   ё        @Trans   @Trans   х        ъ        @Trans   э        @Trans   @Trans
'''

altgr = '''
@None    @None    @None    @None    @None    @None    @None    ₽        @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
'''

altgr_shift = '''
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
@None    @None    @None    @None    @None    @None    @None    @None    @None    @None
'''
